version: '2.2'
services:
  es01:
    image: elastic/elasticsearch:7.10.0
    container_name: v-ramp-es
    environment:
      - node.name=v-ramp-es01
      - cluster.name=v-ramp-es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - rampsearch

  v-ramp:
    container_name: v-ramp
    build:
      context: ./v-front
      dockerfile: Dockerfile
    volumes:
      - './v-front:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - rampsearch

volumes:
  data01:
    driver: local

networks:
  rampsearch:
    driver: bridge